name: movie_browser
description: Flutter movie browser.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_lints: ^1.0.4
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  http: ^0.13.3
  injectable: ^1.5.3
  intl: ^0.17.0
  json_annotation: ^4.4.0

dev_dependencies:
  bloc_test: ^9.0.2
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  freezed_annotation: ^1.1.0
  injectable_generator: ^1.5.2
  json_serializable: ^6.1.4
  mocktail: ^0.2.0

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  main_locale: en_US
